include ../../../theos/makefiles/common.mk

SUBPROJECT_NAME = ASIHTTPRequest
ASIHTTPRequest_FILES = AEYTASIAuthenticationDialog.m AEYTASIDataCompressor.m AEYTASIDataDecompressor.m AEYTASIDownloadCache.m AEYTASIFormDataRequest.m AEYTASIHTTPRequest.m AEYTASIInputStream.m AEYTASINetworkQueue.m AEYTReachability.m

include $(THEOS_MAKE_PATH)/subproject.mk