include ../../theos/makefiles/common.mk

BUNDLE_NAME = YouTube
YouTube_BUNDLE_EXTENSION = assistantExtension
YouTube_FILES = YouTubeCommands.mm YouTubeSnippet.mm
YouTube_INSTALL_PATH = /Library/AssistantExtensions/
YouTube_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/bundle.mk